imports:
    - { resource: services/command_bus.yml }
    - { resource: services/console.yml }
    - { resource: services/game.yml }
    - { resource: services/persistence.yml }
    - { resource: services/query_bus.yml }
    - { resource: services/subscriber.yml }

doctrine:
    dbal:
        connections:
            connect-four:
                url: %connect-four.doctrine.dbal.url%
