services:

    connect-four.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%connect-four.predis.client.url%'
            -
                prefix: 'connect-four.'

    connect-four.message-broker:
        class: Gambling\Common\Port\Adapter\Messaging\GamblingMessageBroker
        public: false
        arguments:
            - '%connect-four.rabbit-mq.dsn%'

    connect-four.event-store:
        class: Gambling\Common\Port\Adapter\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@doctrine.dbal.connect_four_connection'
            - 'event_store'

    connect-four.domain-event-publisher:
        class: Gambling\Common\Domain\DomainEventPublisher
        public: false
        calls:
            - ['subscribe', ['@connect-four.store-domain-events-subscriber']]

    ###############################################
    #           Domain Event Subscriber           #
    ###############################################

    connect-four.store-domain-events-subscriber:
        class: Gambling\ConnectFour\Port\Adapter\Persistence\EventStore\StoreDomainEventsSubscriber
        public: false
        arguments:
            - '@connect-four.event-store'

    ###############################################
    #      Stored Event Subscriber / Commands     #
    ###############################################

    connect-four.build-query-model-command:
        class: Gambling\ConnectFour\Port\Adapter\Console\BuildQueryModelCommand
        public: false
        arguments:
            - '@connect-four.event-store'
            - '@connect-four.predis'
        tags:
            -  { name: console.command }

    connect-four.publish-stored-events-to-rabbit-mq-command:
        class: Gambling\ConnectFour\Port\Adapter\Console\PublishStoredEventsToRabbitMqCommand
        public: false
        arguments:
            - '@connect-four.event-store'
            - '@connect-four.predis'
            - '@connect-four.message-broker'
        tags:
            -  { name: console.command }

    connect-four.referee-command:
        class: Gambling\ConnectFour\Port\Adapter\Console\RefereeCommand
        public: false
        arguments:
            - '@connect-four.message-broker'
            - '@connect-four.command-bus'
        tags:
            -  { name: console.command }

    ###############################################
    #               Game aggregate                #
    ###############################################

    connect-four.game-controller:
        class: Gambling\ConnectFour\Port\Adapter\Http\GameController
        public: false
        arguments:
            - '@connect-four.command-bus'
            - '@connect-four.query-bus'

    connect-four.game-repository:
        class: Gambling\ConnectFour\Port\Adapter\Persistence\Repository\DoctrineJsonGameRepository
        public: false
        arguments:
            - '@doctrine.dbal.connect_four_connection'
            - '@connect-four.domain-event-publisher'

    connect-four.game-finder:
        class: Gambling\ConnectFour\Port\Adapter\Persistence\Repository\PredisGameFinder
        public: false
        arguments:
            - '@connect-four.predis'

    connect-four.games-by-player-finder:
        class: Gambling\ConnectFour\Port\Adapter\Persistence\Repository\PredisGamesByPlayerFinder
        public: false
        arguments:
            - '@connect-four.predis'

    connect-four.open-games-finder:
        class: Gambling\ConnectFour\Port\Adapter\Persistence\Repository\PredisOpenGamesFinder
        public: false
        arguments:
            - '@connect-four.predis'

    connect-four.running-games-finder:
        class: Gambling\ConnectFour\Port\Adapter\Persistence\Repository\PredisRunningGamesFinder
        public: false
        arguments:
            - '@connect-four.predis'
