services:

    # The following definitions decorate the application life cycle. This could be done with a factory object.
    chat.application-life-cycle:
        class: Gaming\Common\Port\Adapter\Application\DoctrineReconnectApplicationLifeCycle
        public: false
        arguments:
            - '@chat.doctrine-transactional-application-life-cycle'
            - '@chat.doctrine-dbal'
            - 300

    chat.doctrine-transactional-application-life-cycle:
        class: Gaming\Common\Port\Adapter\Application\DoctrineTransactionalApplicationLifeCycle
        public: false
        arguments:
            - '@chat.doctrine-dbal'
