services:

    chat.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%env(GAMBLING_CHAT_PREDIS_CLIENT_URL)%'
            -
                prefix: 'chat.'

    chat.doctrine-dbal:
        alias: 'doctrine.dbal.chat_connection'

    chat.message-broker:
        class: Gambling\Common\Port\Adapter\Messaging\GamblingMessageBroker
        public: false
        arguments:
            - '%env(GAMBLING_CHAT_RABBIT_MQ_DSN)%'

    chat.event-store:
        class: Gambling\Common\Port\Adapter\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@chat.doctrine-dbal'
            - 'event_store'
