services:

    chat.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%chat.predis.client.url%'
            -
                prefix: 'chat.'

    chat.doctrine-dbal:
        alias: 'doctrine.dbal.chat_connection'

    chat.message-broker:
        class: Gambling\Common\Port\Adapter\Messaging\GamblingMessageBroker
        public: false
        arguments:
            - '%chat.rabbit-mq.dsn%'

    chat.event-store:
        class: Gambling\Common\Port\Adapter\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@chat.doctrine-dbal'
            - 'event_store'
