services:

    web-interface.message-broker:
        class: Gaming\Common\Port\Adapter\Messaging\GamingMessageBroker
        public: false
        arguments:
            - '%env(APPLICATION_WEB_INTERFACE_RABBIT_MQ_DSN)%'

    web-interface.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%env(APPLICATION_WEB_INTERFACE_PREDIS_CLIENT_URL)%'
            -
                prefix: 'web-interface.'

    web-interface.session-handler:
        class: Gaming\WebInterface\Infrastructure\Persistence\PredisSessionHandler
        public: false
        arguments:
            - '@web-interface.predis'
            - 'session_'
            - 86400
