language: php

php:
    - 7.1
    - 7.2

install:
    - composer install
    - mkdir -p build/logs

script:
    - code/vendor/bin/phpunit --configuration code/phpunit.xml.dist --coverage-clover build/logs/clover.xml
    - code/vendor/bin/phpcs code/tests code/src --standard=PSR2

after_success:
    - travis_retry code/vendor/bin/coveralls -v
