sudo: required

services:
    - docker

language: php

php:
    - 7.2

env:
    global:
        # DOCKER_USERNAME
        - secure: foy6r1CszYf2EbdFwMbSB/5AmQ7jyynckwEkfvXGzbdJ9gdXUNL6VsE1itIXAhIDz8pv1N93Uns7ASdiifMOrlQtgAO9gdziEYRz4DCgOd24oMlPQ9JhT6ghSuj0hMU/l4E4/DUk411hW0L3hBrMokcGpKrhq9v7SefM015GzhGq+qFiAx2jydTu14/xOGlPFnwvISFGLFnnfpO1hunariX8WyHVt/MyF3wZst7g/IeTdC3q7rpmMTLIrnqvZT0X9vuckKUkEEQ19I8OfDu+wPGb0hBWP7/B+xap3qnyy+4pkE2ZzMJvdCljim51c/2NzHICQ0//sSin9S0Ogf8OsLD7JvqzT6HY76spLzWOGuX8mKlPYT/obR5L42jcQtgau0jugBG1yMYmD437cUgpwsSvq/M5VGFgWUKVoivZ4EOMDNcE5ypNd8RkoyWf02CdS6ww302tbsWVmPPSN6ktj83da3jwejLqmury7fUmmI6sbmQK4Zttrtu8ye7MBmu8PL2NaBI6xz4qrMx0naOmasJS+ujHCu96Qw1yEN+HnvAkqhftESpnhKfEm1Uon/YxQB30/8j8Wlalao11DPViqM0iV6gTypLMtAlSVH/+qlWeAsZfDY+cUOIz+5iUrC2pp4+BUA418jmqtwyV5JhAx7cUzdHIybJlIeukmqk188g=
        # DOCKER_PASSWORD
        - secure: xZOsnT0NAWqO+aPq1FFjEXwGSXZtlCSGI+AIMwAeNMqqtf1eElkEEMfPfpj8ck4cAZ/EcSuCjPWvmo3rBJwgTzfn+Nj4vnb2WO/sa5nk4rSNywQrz07I7NeSFEfZY1cD6rADOrRKNB2Bapx4h7gBCMxEL7RBEfr5tERo5kttOgMOPp9hmplj2eQTWlcFo/jNNMQ8B56muG8QQpqkmHn9B0wRck4sjRMLM1YGI1418TnZ5sTf9cQBviVqH+n+k123RSrRYgU8m3LG6QdULyPQxsV9smadii1mk+oGWi3Ula0JVfs7HCCpvJo/4zJow4CH/Q/XYrrgtRBL1gHJ2lCTKeuoY2RT3ov1KcuMxxh+n+4pO+MFKOyl2TInydCuyGmaN2phB3FzjXPv7q11WqCH8xzr/juHebOTvQ50sNZHZEwXZelynvwLcE+1ejVxkVodQQwuKoSqaK762X18+srn1tSKqKgHL5OCWBb39vhvdz5CGNfr+5R8axrMKL/BvxWyqYNrEJqseFDvF3eua/byaCHw7lJmfq7j/aT4os0fDp9/raeHHRjoht/ebbuzJCcE4WGv0/asrgKRx4wczhNuVEE3BZbXzLH3XuyLgg7x/nJ2utJe0asly3GfjL5KyztbPKK/LdGhsHKBezKGKxg5jUbWN6QGpgnPGOE1edWUOaA=

before_install:
    - cd code

install:
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/phpcs tests src --standard=PSR2

after_success:
    - travis_retry vendor/bin/php-coveralls -v
    - cd ..

deploy:
    provider: script
    script: bash docker-push
    on:
       branch: master
