version: '3.4'

services:
    ##############################
    #  Database and application  #
    ##############################
    traefik:
        build:
            context: .
            dockerfile: ./container/traefik/Dockerfile
        command: --api --docker
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=false"
    mysql:
        build:
            context: .
            dockerfile: ./container/mysql/Dockerfile
        command: mysqld
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
           - mysql:/var/lib/mysql
        restart: on-failure
        labels:
            - "traefik.enable=false"
    redis:
        build:
            context: .
            dockerfile: ./container/redis/Dockerfile
        command: redis-server --appendonly yes
        volumes:
            - redis:/data
        restart: on-failure
        labels:
            - "traefik.enable=false"
    rabbit-mq:
        build:
            context: .
            dockerfile: ./container/rabbit-mq/Dockerfile
        hostname: rabbit-mq
        ports:
            - "15672:15672"
        volumes:
            - rabbit-mq:/var/lib/rabbitmq/mnesia
        restart: on-failure
        labels:
            - "traefik.enable=false"
    nchan:
        build:
            context: .
            dockerfile: ./container/nchan/Dockerfile
        links:
            - redis
        restart: on-failure
        labels:
            - "traefik.priority=20"
            - "traefik.frontend.rule=PathPrefix:/sse"
    nginx:
        build:
            context: .
            dockerfile: ./container/nginx/Dockerfile
        links:
            - php-fpm
        volumes:
            - frontend:/project/web
        restart: on-failure
        labels:
            - "traefik.priority=10"
            - "traefik.frontend.rule=PathPrefix:/"
    php-fpm:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
            - ./code/tests:/project/tests
            - ./code/var:/project/var
            - vendor:/project/vendor
        restart: on-failure
        labels:
            - "traefik.enable=false"

    ##############################
    #   Long running processes   #
    ##############################
    php-connect-four-build-query-model:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console connect-four:build-query-model --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-connect-four-publish-stored-events-to-rabbit-mq:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console connect-four:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-chat-publish-stored-events-to-rabbit-mq:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console chat:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-web-interface-publish-running-games-count-to-nchan:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console web-interface:publish-running-games-count-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-web-interface-publish-rabbit-mq-events-to-nchan:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console web-interface:publish-rabbit-mq-events-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-chat-command-listener:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console chat:command-listener --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-connect-four-referee:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: /project/bin/console connect-four:referee --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"

    ##############################
    #     Development helper     #
    ##############################
    frontend-builder:
        build:
            context: .
            dockerfile: ./container/nginx/Dockerfile
            target: builder
        working_dir: /project
        volumes:
            - ./code/src:/project/src
            - frontend:/project/web
        labels:
            - "traefik.enable=false"
    php:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        entrypoint: docker-php-entrypoint
        volumes:
            - ./code/src:/project/src
            - ./code/tests:/project/tests
            - vendor:/project/vendor
        labels:
            - "traefik.enable=false"
    composer:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
            target: builder
        working_dir: /project
        volumes:
            - ./code/composer.json:/project/composer.json
            - ./code/composer.lock:/project/composer.lock
            - vendor:/project/vendor
        labels:
            - "traefik.enable=false"

volumes:
    frontend:
    vendor:
    mysql:
    redis:
    rabbit-mq:
