version: '3.4'

services:
    ##############################
    #  Database and application  #
    ##############################
    traefik:
        build:
            context: .
            dockerfile: ./container/traefik/Dockerfile
        ports:
            - "80:80"
            - "8080:8080"
        links:
            - nchan
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    mysql:
        build:
            context: .
            dockerfile: ./container/mysql/Dockerfile
        command: mysqld
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql:/var/lib/mysql
        restart: on-failure
    redis:
        build:
            context: .
            dockerfile: ./container/redis/Dockerfile
        command: redis-server --appendonly yes
        volumes:
            - redis:/data
        restart: on-failure
    rabbit-mq:
        build:
            context: .
            dockerfile: ./container/rabbit-mq/Dockerfile
        hostname: rabbit-mq
        ports:
            - "8083:15672"
        volumes:
            - rabbit-mq:/var/lib/rabbitmq/mnesia
        restart: on-failure
    nchan:
        build:
            context: .
            dockerfile: ./container/nchan/Dockerfile
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.priority=20"
            - "traefik.frontend.rule=PathPrefix:/sse"
    nginx:
        build:
            context: .
            dockerfile: ./container/nginx/Dockerfile
        links:
            - php-fpm
        volumes:
            - ./code/web/assets:/project/web/assets
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.priority=10"
            - "traefik.frontend.rule=PathPrefix:/"
    php-fpm:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
            - ./code/tests:/project/tests
            - ./code/var:/project/var
            - vendor:/project/vendor
        restart: on-failure

    ##############################
    #   Long running processes   #
    ##############################
    php-connect-four-build-query-model:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console connect-four:build-query-model --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-connect-four-publish-stored-events-to-rabbit-mq:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console connect-four:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-chat-publish-stored-events-to-rabbit-mq:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console chat:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-identity-publish-stored-events-to-rabbit-mq:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console identity:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-web-interface-publish-running-games-count-to-nchan:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console web-interface:publish-running-games-count-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-web-interface-publish-rabbit-mq-events-to-nchan:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console web-interface:publish-rabbit-mq-events-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-chat-command-listener:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console chat:command-listener --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure
    php-connect-four-referee:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        command: bin/restartOnChange /project/bin/console connect-four:referee --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        volumes:
            - ./code/config:/project/config
            - ./code/src:/project/src
        restart: on-failure

    ##############################
    #     Development helper     #
    ##############################
    php:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
        entrypoint: docker-php-entrypoint
        volumes:
            - ./code/src:/project/src
            - ./code/tests:/project/tests
            - vendor:/project/vendor
    composer:
        build:
            context: .
            dockerfile: ./container/php-fpm/Dockerfile
            target: builder
        working_dir: /project
        volumes:
            - ./code/composer.json:/project/composer.json
            - ./code/composer.lock:/project/composer.lock
            - vendor:/project/vendor
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: password
        ports:
            - "8081:80"
        links:
            - mysql
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        environment:
            REDIS_1_HOST: redis
        ports:
            - "8082:80"
        links:
            - redis

volumes:
    vendor:
    mysql:
    redis:
    rabbit-mq:
