version: '3.4'

services:
    ##############################
    #  Database and application  #
    ##############################
    traefik:
        image: marein/php-gambling-website:traefik
        command: --api --docker
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=false"
    mysql:
        image: marein/php-gambling-website:mysql
        command: mysqld
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql:/var/lib/mysql
        restart: on-failure
        labels:
            - "traefik.enable=false"
    redis:
        image: marein/php-gambling-website:redis
        command: redis-server --appendonly yes
        volumes:
            - redis:/data
        restart: on-failure
        labels:
            - "traefik.enable=false"
    rabbit-mq:
        image: marein/php-gambling-website:rabbit-mq
        hostname: rabbit-mq
        volumes:
            - rabbit-mq:/var/lib/rabbitmq/mnesia
        restart: on-failure
        labels:
            - "traefik.enable=false"
    nchan:
        image: marein/php-gambling-website:nchan
        links:
            - redis
        restart: on-failure
        labels:
            - "traefik.priority=20"
            - "traefik.frontend.rule=PathPrefix:/sse"
    nginx:
        image: marein/php-gambling-website:nginx
        links:
            - php-fpm
        restart: on-failure
        labels:
            - "traefik.priority=10"
            - "traefik.frontend.rule=PathPrefix:/"
    php-fpm:
        image: marein/php-gambling-website:php-fpm
        environment:
            GAMBLING_ENVIRONMENT: prod
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"

    ##############################
    #   Long running processes   #
    ##############################
    php-connect-four-build-query-model:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console connect-four:build-query-model --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-connect-four-publish-stored-events-to-rabbit-mq:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console connect-four:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-chat-publish-stored-events-to-rabbit-mq:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console chat:publish-stored-events-to-rabbit-mq --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-web-interface-publish-running-games-count-to-nchan:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console web-interface:publish-running-games-count-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-web-interface-publish-rabbit-mq-events-to-nchan:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console web-interface:publish-rabbit-mq-events-to-nchan --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-chat-command-listener:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console chat:command-listener --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"
    php-connect-four-referee:
        image: marein/php-gambling-website:php-fpm
        command: /project/bin/console connect-four:referee --env=prod
        environment:
            WAIT_FOR: mysql:3306,redis:6379,rabbit-mq:5672,nchan:81
        links:
            - mysql
            - redis
            - rabbit-mq
            - nchan
        restart: on-failure
        labels:
            - "traefik.enable=false"

volumes:
    mysql:
    redis:
    rabbit-mq:
