imports:
    - { resource: config.yml }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: "%kernel.project_dir%/config/routing_dev.yml"

web_profiler:
    toolbar: true
