services:

    # The following definitions decorate the callable command bus. This could be done with a factory object.
    connect-four.command-bus:
        class: Gambling\Common\Port\Adapter\Bus\DoctrineReconnectBus
        public: false
        arguments:
            - '@connect-four.retry-command-bus'
            - '@connect-four.doctrine-dbal'
            - 300

    connect-four.retry-command-bus:
        class: Gambling\Common\Bus\RetryBus
        public: false
        arguments:
            - '@connect-four.doctrine-transactional-command-bus'
            - 3
            - 'Gambling\Common\Domain\Exception\ConcurrencyException'

    connect-four.doctrine-transactional-command-bus:
        class: Gambling\Common\Port\Adapter\Bus\DoctrineTransactionalBus
        public: false
        arguments:
            - '@connect-four.callable-command-bus'
            - '@connect-four.doctrine-dbal'

    # This is pretty ugly. We can use tags, or create this via a factory in php.
    connect-four.callable-command-bus:
        class: Gambling\Common\Bus\CallableBus
        public: false
        calls:
            - [
                addHandler,
                [
                  'Gambling\ConnectFour\Application\Game\Command\AbortCommand',
                  '@connect-four.command.abort-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gambling\ConnectFour\Application\Game\Command\ResignCommand',
                  '@connect-four.command.resign-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gambling\ConnectFour\Application\Game\Command\AssignChatCommand',
                  '@connect-four.command.assign-chat-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gambling\ConnectFour\Application\Game\Command\JoinCommand',
                  '@connect-four.command.join-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gambling\ConnectFour\Application\Game\Command\MoveCommand',
                  '@connect-four.command.move-handler'
                ]
              ]
            - [
                addHandler,
                [
                  'Gambling\ConnectFour\Application\Game\Command\OpenCommand',
                  '@connect-four.command.open-handler'
                ]
              ]

    connect-four.command.abort-handler:
        class: Gambling\ConnectFour\Application\Game\Command\AbortHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.resign-handler:
        class: Gambling\ConnectFour\Application\Game\Command\ResignHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.assign-chat-handler:
        class: Gambling\ConnectFour\Application\Game\Command\AssignChatHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.join-handler:
        class: Gambling\ConnectFour\Application\Game\Command\JoinHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.move-handler:
        class: Gambling\ConnectFour\Application\Game\Command\MoveHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.open-handler:
        class: Gambling\ConnectFour\Application\Game\Command\OpenHandler
        public: false
        arguments:
            - '@connect-four.game-repository'
