services:

    connect-four.build-query-model-command:
        class: Gambling\ConnectFour\Port\Adapter\Console\BuildQueryModelCommand
        public: false
        arguments:
            - '@connect-four.event-store'
            - '@connect-four.predis'
        tags:
            -  { name: console.command }

    connect-four.publish-stored-events-to-rabbit-mq-command:
        class: Gambling\ConnectFour\Port\Adapter\Console\PublishStoredEventsToRabbitMqCommand
        public: false
        arguments:
            - '@connect-four.event-store'
            - '@connect-four.predis'
            - '@connect-four.message-broker'
        tags:
            -  { name: console.command }

    connect-four.referee-command:
        class: Gambling\ConnectFour\Port\Adapter\Console\RefereeCommand
        public: false
        arguments:
            - '@connect-four.message-broker'
            - '@connect-four.command-bus'
        tags:
            -  { name: console.command }
