services:

    # The following definitions decorate the application life cycle. This could be done with a factory object.
    identity.application-life-cycle:
        class: Gambling\Common\Port\Adapter\Application\DoctrineReconnectApplicationLifeCycle
        public: false
        arguments:
            - '@identity.doctrine-transactional-application-life-cycle'
            - '@identity.doctrine-dbal'
            - 300

    identity.doctrine-transactional-application-life-cycle:
        class: Gambling\Common\Port\Adapter\Application\DoctrineTransactionalApplicationLifeCycle
        public: false
        arguments:
            - '@identity.doctrine-dbal'
