imports:
    - { resource: services/application_life_cycle.yml }
    - { resource: services/persistence.yml }
    - { resource: services/subscriber.yml }
    - { resource: services/user.yml }

doctrine:
    dbal:
        connections:
            user:
                url: %user.doctrine.dbal.url%
    orm:
        entity_managers:
            user:
                connection: user
                mappings:
                    user:
                        type:     yml
                        dir:      %kernel.root_dir%/../src/User/Port/Adapter/Persistence/Mapping/User
                        prefix:   Gambling\User\Domain\Model\User
