services:

    user.application-life-cycle:
        class: Gambling\User\Application\ApplicationLifeCycle
        public: false
        arguments:
            - '@doctrine.dbal.user_connection'

    user.event-store:
        class: Gambling\Common\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@doctrine.dbal.user_connection'
            - 'event_store'

    user.user-service:
        class: Gambling\User\Application\User\UserService
        public: false
        arguments:
            - '@user.application-life-cycle'
            - '@user.user-repository'

    user.user-controller:
        class: Gambling\User\Port\Adapter\Http\UserController
        public: false
        arguments:
            - '@user.user-service'

    user.domain-event-publisher:
        class: Gambling\Common\Domain\DomainEventPublisher
        public: false
        calls:
            - ['subscribe', ['@user.store-domain-events-subscriber']]

    user.user-repository:
        class: Gambling\User\Port\Adapter\Persistence\Repository\DoctrineUserRepository
        public: false
        arguments:
            - '@doctrine.orm.user_entity_manager'
            - '@user.domain-event-publisher'

    ###############################################
    #           Domain Event Subscriber           #
    ###############################################

    user.store-domain-events-subscriber:
        class: Gambling\User\Port\Adapter\Persistence\EventStore\StoreDomainEventsSubscriber
        public: false
        arguments:
            - '@user.event-store'
