services:

    web-interface.message-broker:
        class: Gambling\Common\Port\Adapter\Messaging\GamblingMessageBroker
        public: false
        arguments:
            - '%web-interface.rabbit-mq.dsn%'

    ###############################################
    #                   Session                   #
    ###############################################

    web-interface.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%web-interface.predis.client.url%'
            -
                prefix: 'web-interface.'

    web-interface.session-handler:
        class: Gambling\WebInterface\Infrastructure\Persistence\PredisSessionHandler
        public: false
        arguments:
            - '@web-interface.predis'
            - 'session_'
            - 86400

    ###############################################
    #             Application Service             #
    ###############################################

    web-interface.chat-service:
        class: Gambling\WebInterface\Infrastructure\Integration\DirectControllerInvocationChatService
        public: false
        arguments:
            - '@chat.chat-controller'

    web-interface.connect-four-service:
        class: Gambling\WebInterface\Infrastructure\Integration\DirectControllerInvocationConnectFourService
        public: false
        arguments:
            - '@connect-four.game-controller'

    web-interface.user-service:
        class: Gambling\WebInterface\Infrastructure\Integration\DirectControllerInvocationUserService
        public: false
        arguments:
            - '@user.user-controller'

    web-interface.browser-notifier:
        class: Gambling\WebInterface\Infrastructure\NchanBrowserNotifier
        public: false
        arguments:
            - '%web-interface.nchan.base.url%'
            - '%web-interface.nchan.username%'
            - '%web-interface.nchan.password%'

    ###############################################
    #                EventListener                #
    ###############################################

    web-interface.assign-user-id-on-kernel-request:
        class: Gambling\WebInterface\Infrastructure\EventListener\AssignUserIdOnKernelRequest
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    web-interface.exception-to-json-listener:
        class: Gambling\WebInterface\Infrastructure\EventListener\ExceptionToJsonListener
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    ###############################################
    #                 Controller                  #
    ###############################################

    web-interface.page-controller:
        class: Gambling\WebInterface\Presentation\Http\PageController
        arguments:
            - '@templating'
            - '@web-interface.connect-four-service'

    web-interface.chat-controller:
        class: Gambling\WebInterface\Presentation\Http\ChatController
        arguments:
            - '@web-interface.chat-service'

    web-interface.connect-four-controller:
        class: Gambling\WebInterface\Presentation\Http\ConnectFourController
        arguments:
            - '@web-interface.connect-four-service'

    web-interface.user-controller:
        class: Gambling\WebInterface\Presentation\Http\UserController
        arguments:
            - '@web-interface.user-service'

    ###############################################
    #      Message Broker Consumer / Commands     #
    ###############################################

    web-interface.publish-rabbit-mq-events-to-nchan:
        class: Gambling\WebInterface\Presentation\Console\PublishRabbitMqEventsToNchanCommand
        public: false
        arguments:
            - '@web-interface.message-broker'
            - '@web-interface.browser-notifier'
        tags:
            -  { name: console.command }

    web-interface.publish-running-games-count-to-nchan-command:
        class: Gambling\WebInterface\Presentation\Console\PublishRunningGamesCountToNchanCommand
        public: false
        arguments:
            - '@web-interface.connect-four-service'
            - '@web-interface.browser-notifier'
        tags:
            -  { name: console.command }
