services:

    # The following definitions decorate the application life cycle. This could be done with a factory object.
    identity.application-life-cycle:
        class: Gaming\Common\Port\Adapter\Application\DoctrineReconnectApplicationLifeCycle
        public: false
        arguments:
            - '@identity.retry-application-life-cycle'
            - '@identity.doctrine-dbal'
            - 300

    identity.retry-application-life-cycle:
        class: Gaming\Common\Application\RetryApplicationLifeCycle
        public: false
        arguments:
            - '@identity.doctrine-transactional-application-life-cycle'
            - 3
            - 'Gaming\Common\Domain\Exception\ConcurrencyException'

    identity.doctrine-transactional-application-life-cycle:
        class: Gaming\Common\Port\Adapter\Application\DoctrineTransactionalApplicationLifeCycle
        public: false
        arguments:
            - '@identity.doctrine-dbal'
