imports:
    - { resource: services/application_life_cycle.yml }
    - { resource: services/chat.yml }
    - { resource: services/console.yml }
    - { resource: services/persistence.yml }

doctrine:
    dbal:
        connections:
            chat:
                url: '%env(GAMBLING_CHAT_DOCTRINE_DBAL_URL)%'
                charset: utf8mb4
                default_table_options:
                     charset: utf8mb4
                     collate: utf8mb4_unicode_ci
