services:

    chat.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%chat.predis.client.url%'
            -
                prefix: 'chat.'

    chat.message-broker:
        class: Gambling\Common\Port\Adapter\Messaging\GamblingMessageBroker
        public: false
        arguments:
            - '%chat.rabbit-mq.dsn%'

    chat.event-store:
        class: Gambling\Common\Port\Adapter\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@doctrine.dbal.chat_connection'
            - 'event_store'

    ###############################################
    #      Stored Event Subscriber / Commands     #
    ###############################################

    chat.publish-stored-events-to-rabbit-mq-command:
        class: Gambling\Chat\Presentation\Console\PublishStoredEventsToRabbitMqCommand
        public: false
        arguments:
            - '@chat.event-store'
            - '@chat.predis'
            - '@chat.message-broker'
        tags:
            -  { name: console.command }

    chat.rabbit-mq-command-listener-command:
        class: Gambling\Chat\Presentation\Console\RabbitMqCommandListenerCommand
        public: false
        arguments:
            - '@chat.message-broker'
            - '@chat.chat-service'
        tags:
            -  { name: console.command }

    ###############################################
    #                    Chat                     #
    ###############################################

    chat.chat-gateway:
        class: Gambling\Chat\Infrastructure\DoctrineChatGateway
        public: false
        arguments:
            - '@doctrine.dbal.chat_connection'

    chat.application-life-cycle-factory:
        class: Gambling\Chat\Application\ApplicationLifeCycleFactory
        public: false
        arguments:
            - '@doctrine.dbal.chat_connection'

    chat.application-life-cycle:
        class: Gambling\Common\Application\ApplicationLifeCycle
        public: false
        factory: 'chat.application-life-cycle-factory:create'

    chat.chat-service:
        class: Gambling\Chat\Application\ChatService
        public: false
        arguments:
            - '@chat.application-life-cycle'
            - '@chat.chat-gateway'
            - '@chat.event-store'

    chat.chat-controller:
        class: Gambling\Chat\Presentation\Http\ChatController
        public: false
        arguments:
            - '@chat.chat-service'
