services:

    identity.store-domain-events-subscriber:
        class: Gaming\Identity\Port\Adapter\Persistence\EventStore\StoreDomainEventsSubscriber
        public: false
        arguments:
            - '@identity.event-store'
