services:

    web-interface.chat-service:
        class: Gambling\WebInterface\Infrastructure\Integration\DirectControllerInvocationChatService
        public: false
        arguments:
            - '@chat.chat-controller'

    web-interface.connect-four-service:
        class: Gambling\WebInterface\Infrastructure\Integration\DirectControllerInvocationConnectFourService
        public: false
        arguments:
            - '@connect-four.game-controller'

    web-interface.user-service:
        class: Gambling\WebInterface\Infrastructure\Integration\DirectControllerInvocationUserService
        public: false
        arguments:
            - '@user.user-controller'

    web-interface.browser-notifier:
        class: Gambling\WebInterface\Infrastructure\NchanBrowserNotifier
        public: false
        arguments:
            - '%env(GAMBLING_WEB_INTERFACE_NCHAN_BASE_URL)%'
            - '%env(GAMBLING_WEB_INTERFACE_NCHAN_USERNAME)%'
            - '%env(GAMBLING_WEB_INTERFACE_NCHAN_PASSWORD)%'
