imports:
    - { resource: chat/config.yml }
    - { resource: connect-four/config.yml }
    - { resource: identity/config.yml }
    - { resource: web-interface/config.yml }

framework:
    secret: '%env(GAMBLING_KERNEL_SECRET)%'
    templating:
        engines: ['twig']
    router:
        resource: "%kernel.root_dir%/config/routing.yml"

doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
        mapping_types:
            uuid_binary_ordered_time: binary
            uuid_binary: binary

services:
    # Custom exception listener for the gambling domain.
    # Lower priority so that the profiler is respected.
    gambling.exception-to-json-listener:
        class: Gambling\Common\Port\Adapter\Symfony\GamblingExceptionListener
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -100 }
