imports:
    - { resource: chat/config.yml }
    - { resource: chat/services.yml }
    - { resource: connect-four/config.yml }
    - { resource: connect-four/services.yml }
    - { resource: connect-four/services_query_bus.yml }
    - { resource: connect-four/services_command_bus.yml }
    - { resource: user/config.yml }
    - { resource: user/services.yml }
    - { resource: web-interface/config.yml }
    - { resource: web-interface/services.yml }

framework:
    secret: %kernel.secret%
    templating:
        engines: ['twig']
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
