imports:
    - { resource: chat/config.yml }
    - { resource: connect-four/config.yml }
    - { resource: user/config.yml }
    - { resource: web-interface/config.yml }

framework:
    secret: '%env(GAMBLING_KERNEL_SECRET)%'
    templating:
        engines: ['twig']
    router:
        resource: "%kernel.root_dir%/config/routing.yml"

doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
            uuid_binary_ordered_time: binary
