services:

    connect-four.domain-event-publisher:
        class: Gaming\Common\Domain\DomainEventPublisher
        public: false
        calls:
            - ['subscribe', ['@connect-four.store-domain-events-subscriber']]

    connect-four.game-controller:
        class: Gaming\ConnectFour\Port\Adapter\Http\GameController
        public: false
        arguments:
            - '@connect-four.command-bus'
            - '@connect-four.query-bus'

    connect-four.game-repository:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Repository\DoctrineJsonGameRepository
        public: false
        arguments:
            - '@connect-four.doctrine-dbal'
            - '@connect-four.domain-event-publisher'

    connect-four.game-store:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Repository\PredisGameStore
        public: false
        arguments:
            - '@connect-four.predis'
            - '@connect-four.event-store-game-finder'

    connect-four.game-finder:
        alias: 'connect-four.game-store'

    connect-four.event-store-game-finder:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Repository\EventStoreGameFinder
        public: false
        arguments:
            - '@connect-four.event-store'

    connect-four.games-by-player-finder:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Repository\PredisGamesByPlayerFinder
        public: false
        arguments:
            - '@connect-four.predis'

    connect-four.open-games-finder:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Repository\PredisOpenGamesFinder
        public: false
        arguments:
            - '@connect-four.predis'

    connect-four.running-games-finder:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Repository\PredisRunningGamesFinder
        public: false
        arguments:
            - '@connect-four.predis'

    connect-four.game-projection:
        class: Gaming\ConnectFour\Port\Adapter\Persistence\Projection\GameProjection
        public: false
        arguments:
            - '@connect-four.game-store'
