services:

    connect-four.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%env(GAMBLING_CONNECT_FOUR_PREDIS_CLIENT_URL)%'
            -
                prefix: 'connect-four.'

    connect-four.doctrine-dbal:
        alias: 'doctrine.dbal.connect_four_connection'

    connect-four.message-broker:
        class: Gambling\Common\Port\Adapter\Messaging\GamblingMessageBroker
        public: false
        arguments:
            - '%env(GAMBLING_CONNECT_FOUR_RABBIT_MQ_DSN)%'

    connect-four.event-store:
        class: Gambling\Common\Port\Adapter\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@connect-four.doctrine-dbal'
            - 'event_store'
